lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key : '%env(resolve:JWT_PUBLIC_KEY)%'  # required for token verification
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%' # required for token creation, usage of an environment variable is recommended
    token_ttl: '%env(resolve:JWT_TOKENTTL)%'