version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./application:/app
    depends_on:
      - app-php-fpm
    ports:
      - "8081:80"
  app-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./application:/app
      - ./storage:/app/var/storage
    depends_on:
      - rabbitmq
  app-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./application:/app
    depends_on:
      - rabbitmq
    command: composer install --no-interaction --no-cache
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  queue-tracker-worker:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./application:/app
    restart: on-failure
    depends_on:
      - app-php-cli
      - rabbitmq
    command: php /app/bin/console messenger:consume tracker -vv

volumes:
  rabbitmq-data: