<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ABzXAQNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ABzXAQN' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Queue/Consumer/User/TrackActionHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/socialtechio/slow-storage-emulator/src/StorageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/socialtechio/slow-storage-emulator/src/SlowStorage.php';

        return $container->privates['.messenger.handler_descriptor.ABzXAQN'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Queue\Consumer\User\TrackActionHandler(new \SocialTech\SlowStorage(), ($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $container->getEnv('resolve:TRACKING_STORAGE_PATH'), 'json', ','), []);
    }
}
