<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QRwnsv3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QRwnsv3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QRwnsv3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\Auth\\RegistrationController::request' => ['privates', '.service_locator.7zYWpXv', 'get_ServiceLocator_7zYWpXvService', true],
            'App\\Controller\\Api\\Profile\\UserProfile::show' => ['privates', '.service_locator.1x_2qPf', 'get_ServiceLocator_1x2qPfService', true],
            'App\\Controller\\Api\\Tracker\\TrackingController::track' => ['privates', '.service_locator.PmVqrnj', 'get_ServiceLocator_PmVqrnjService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Api\\Auth\\RegistrationController:request' => ['privates', '.service_locator.7zYWpXv', 'get_ServiceLocator_7zYWpXvService', true],
            'App\\Controller\\Api\\Profile\\UserProfile:show' => ['privates', '.service_locator.1x_2qPf', 'get_ServiceLocator_1x2qPfService', true],
            'App\\Controller\\Api\\Tracker\\TrackingController:track' => ['privates', '.service_locator.PmVqrnj', 'get_ServiceLocator_PmVqrnjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Api\\Auth\\RegistrationController::request' => '?',
            'App\\Controller\\Api\\Profile\\UserProfile::show' => '?',
            'App\\Controller\\Api\\Tracker\\TrackingController::track' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Api\\Auth\\RegistrationController:request' => '?',
            'App\\Controller\\Api\\Profile\\UserProfile:show' => '?',
            'App\\Controller\\Api\\Tracker\\TrackingController:track' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
