<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7zYWpXvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7zYWpXv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7zYWpXv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'handler' => ['privates', 'App\\Model\\User\\UseCase\\Registration\\Request\\Handler', 'getHandlerService', true],
        ], [
            'handler' => 'App\\Model\\User\\UseCase\\Registration\\Request\\Handler',
        ]);
    }
}
