<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnonymousCreatorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\User\AnonymousCreatorController' shared autowired service.
     *
     * @return \App\Controller\Api\User\AnonymousCreatorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/User/AnonymousCreatorController.php';

        $container->services['App\\Controller\\Api\\User\\AnonymousCreatorController'] = $instance = new \App\Controller\Api\User\AnonymousCreatorController(($container->privates['App\\Service\\AnonymousUser\\AnonymousUser'] ?? $container->load('getAnonymousUserService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Api\\User\\AnonymousCreatorController', $container));

        return $instance;
    }
}
