<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandler2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\User\UseCase\Action\Track\Handler' shared autowired service.
     *
     * @return \App\Model\User\UseCase\Action\Track\Handler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Model/User/UseCase/Action/Track/Handler.php';

        return $container->privates['App\\Model\\User\\UseCase\\Action\\Track\\Handler'] = new \App\Model\User\UseCase\Action\Track\Handler(($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService()));
    }
}
