<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\User\UseCase\Registration\Request\Handler' shared autowired service.
     *
     * @return \App\Model\User\UseCase\Registration\Request\Handler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Model/User/UseCase/Registration/Request/Handler.php';
        include_once \dirname(__DIR__, 4).'/src/Model/User/Service/Contract/PasswordHasherInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Model/User/Service/PasswordHasher.php';

        return $container->privates['App\\Model\\User\\UseCase\\Registration\\Request\\Handler'] = new \App\Model\User\UseCase\Registration\Request\Handler(($container->privates['App\\Model\\User\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), new \App\Model\User\Service\PasswordHasher(), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
