<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_TrackerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.transport.tracker' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/PhpSerializer.php';

        return $container->privates['messenger.transport.tracker'] = (new \Symfony\Component\Messenger\Transport\TransportFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => (new \Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransportFactory());
            yield 1 => (new \Symfony\Component\Messenger\Bridge\Redis\Transport\RedisTransportFactory());
            yield 2 => $container->load('getMessenger_Transport_Sync_FactoryService');
            yield 3 => ($container->privates['messenger.transport.in_memory.factory'] ?? ($container->privates['messenger.transport.in_memory.factory'] = new \Symfony\Component\Messenger\Transport\InMemoryTransportFactory()));
        }, 4)))->createTransport($container->getEnv('MESSENGER_TRANSPORT_DSN'), ['exchange' => ['name' => 'tracker', 'type' => 'fanout'], 'queues' => ['tracker' => NULL], 'transport_name' => 'tracker'], new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer());
    }
}
