<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Auth\RegistrationController' shared autowired service.
     *
     * @return \App\Controller\Api\Auth\RegistrationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Auth/RegistrationController.php';

        $container->services['App\\Controller\\Api\\Auth\\RegistrationController'] = $instance = new \App\Controller\Api\Auth\RegistrationController(($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')), ($container->services['.container.private.validator'] ?? $container->get_Container_Private_ValidatorService()));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Api\\Auth\\RegistrationController', $container));

        return $instance;
    }
}
