<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Tracker\TrackingController' shared autowired service.
     *
     * @return \App\Controller\Api\Tracker\TrackingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Tracker/TrackingController.php';

        $container->services['App\\Controller\\Api\\Tracker\\TrackingController'] = $instance = new \App\Controller\Api\Tracker\TrackingController(($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')), ($container->services['.container.private.validator'] ?? $container->get_Container_Private_ValidatorService()), ($container->privates['App\\Service\\AnonymousUser\\AnonymousUser'] ?? $container->load('getAnonymousUserService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Api\\Tracker\\TrackingController', $container));

        return $instance;
    }
}
