<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Profile\UserProfile' shared autowired service.
     *
     * @return \App\Controller\Api\Profile\UserProfile
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Profile/UserProfile.php';

        $container->services['App\\Controller\\Api\\Profile\\UserProfile'] = $instance = new \App\Controller\Api\Profile\UserProfile();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Api\\Profile\\UserProfile', $container));

        return $instance;
    }
}
