<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFetcherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\ReadModel\User\UserFetcher' shared autowired service.
     *
     * @return \App\ReadModel\User\UserFetcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ReadModel/User/UserFetcher.php';

        return $container->privates['App\\ReadModel\\User\\UserFetcher'] = new \App\ReadModel\User\UserFetcher(($container->privates['App\\Model\\User\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), 'd-m-Y');
    }
}
