<?php

namespace ContainerXonzO1W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\User\Repository\UserRepository' shared autowired service.
     *
     * @return \App\Model\User\Repository\UserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Model/User/Repository/Contract/UserRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Model/User/Repository/UserRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemReader.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemOperator.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Filesystem.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/UnixVisibility/VisibilityConverter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/UnixVisibility/PortableVisibilityConverter.php';
        include_once \dirname(__DIR__, 4).'/src/Model/User/Repository/Hydrator/UserHydratorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Model/User/Repository/Hydrator/UserHydrator.php';

        $a = ($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService'));

        return $container->privates['App\\Model\\User\\Repository\\UserRepository'] = new \App\Model\User\Repository\UserRepository(new \League\Flysystem\Filesystem(new \League\Flysystem\Local\LocalFilesystemAdapter((\dirname(__DIR__, 3).'/storage/auth'), \League\Flysystem\UnixVisibility\PortableVisibilityConverter::fromArray(['file' => ['public' => 420, 'private' => 384], 'dir' => ['public' => 493, 'private' => 448]]), 0, 2), ['visibility' => NULL, 'case_sensitive' => true, 'disable_asserts' => false]), new \App\Model\User\Repository\Hydrator\UserHydrator('Y-m-d\\TH:i:sP'), $a, $a, 'json');
    }
}
