framework:
    messenger:
        transports:
            tracker :
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: tracker
                        type: fanout
                    queues:
                        tracker: ~
        routing:
            App\Queue\Message\Message\TrackAction: tracker

