security:
    enable_authenticator_manager: true

    providers:
        custom_provider:
            id: App\Security\UserProvider

    encoders:
        App\Security\User: native

    # ...

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                username_path: nickName
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/auth/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }