<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXonzO1W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXonzO1W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXonzO1W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXonzO1W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXonzO1W\App_KernelDevDebugContainer([
    'container.build_hash' => 'XonzO1W',
    'container.build_id' => 'd129aafe',
    'container.build_time' => 1626358735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXonzO1W');
